spring:
  application:
    name: ledger-service
  data:
    mongodb:
      host: ${MONGO_LEDGER_HOST:localhost}
      port: ${MONGO_LEDGER_PORT:27017}
      database: ${MONGO_LEDGER_DB:ledger_db}
      username: ${MONGO_LEDGER_USER:}
      password: ${MONGO_LEDGER_PASSWORD:}
      authentication-database: admin
      uuid-representation: standard
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  mongodb:
    host: ${MONGO_LEDGER_HOST:localhost}
    port: ${MONGO_LEDGER_PORT:27017}
    database: ${MONGO_LEDGER_DB:ledger_db}
    username: ${MONGO_LEDGER_USER:}
    password: ${MONGO_LEDGER_PASSWORD:}
    authentication-database: admin
    uuid-representation: standard
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ledger-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: "com.fraudetection.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fraudetection.ledger_service.shared.dto.event.KafkaEventEnvelope
    template:
      observation-enabled: true
    listener:
      observation-enabled: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
