spring:
  application:
    name: auth-service
  datasource:
    url: ${POSTGRES_AUTH_URL}
    username: ${POSTGRES_AUTH_USER}
    password: ${POSTGRES_AUTH_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
