spring:
  application:
    name: fraud-detection-service
  datasource:
    url: ${POSTGRES_FRAUD_URL}
    username: ${POSTGRES_FRAUD_USER}
    password: ${POSTGRES_FRAUD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
        spring.json.trusted.packages: com.fraudetection.fraud_detection_service.dto.event
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.fraudetection.fraud_detection_service.dto.event.KafkaEventEnvelope
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  otlp:
    metrics:
      export:
        enabled: false
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: ${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4318/v1/traces}
