services:
  postgres-auth:
    image: postgres:16-alpine
    container_name: fraudshield-postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_AUTH_USER} -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_auth_data:
